x-healthcheck: &default-healthcheck
  test: ["CMD", "curl", "-f", "http://localhost/health.html"]
  interval: 10s
  timeout: 3s
  retries: 3

services:
  web1:
    image: ${REGISTRY_USER}/web1:${IMAGE_TAG}
    restart: unless-stopped
    healthcheck:
      <<: *default-healthcheck

  web2:
    image: ${REGISTRY_USER}/web2:${IMAGE_TAG}
    restart: unless-stopped
    healthcheck:
      <<: *default-healthcheck

  web3:
    image: ${REGISTRY_USER}/web3:${IMAGE_TAG}
    restart: unless-stopped
    healthcheck:
      <<: *default-healthcheck

  nginx-balancer:
    image: ${REGISTRY_USER}/nginx-balancer:${IMAGE_TAG}
    restart: unless-stopped

    ports:
      - "${NGINX_PORT}:80"

    healthcheck:
      <<: *default-healthcheck

    depends_on:
      web1:
        condition: service_healthy
      web2:
        condition: service_healthy
      web3:
        condition: service_healthy
