services:
  web1:
    build: ./web1
    container_name: web1
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 3s
      retries: 3

  web2:
    build: ./web2
    container_name: web2
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 3s
      retries: 3

  web3:
    build: ./web3
    container_name: web3
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx-balancer:
    build: ./balancer
    container_name: nginx-balancer

    ports:
      - "8091:80"

    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 3s
      retries: 3

    depends_on:
      web1:
        condition: service_healthy
      web2:
        condition: service_healthy
      web3:
        condition: service_healthy
