name: Deploy nginx load balancer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check environment
        run: |
          test -f /home/vboxuser/load-balancer.env

      - name: Deploy containers
        run: |
          cd nginx/load-balancer-demo

          docker compose \
            --env-file /home/vboxuser/load-balancer.env \
            --env IMAGE_TAG=${{ github.sha }} \
            pull

          IMAGE_TAG=${{ github.sha }} \
          docker compose \
            --env-file /home/vboxuser/load-balancer.env \
            up -d --force-recreate --remove-orphans

      - name: Check containers
        run: |
          cd nginx/load-balancer-demo

          docker compose \
            --env-file /home/vboxuser/load-balancer.env \
            ps

      - name: Smoke test
        run: |
          curl -f http://localhost:8091
